name: Main
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
  schedule:
    - cron: "0 0 * * *"

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: './bin'
      - name: Install ShellSpec
        run: curl -fsSL https://github.com/shellspec/shellspec/releases/latest/download/shellspec-dist.tar.gz | tar -xz -C ..
      - name: Run Shellspec
        run: bash ../shellspec/shellspec
      - name: Test asdf-vm plugin
        uses: asdf-vm/actions/plugin-test@v1.1.0
        with:
          command: grype version
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
